name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Swiftlint
      run: |
        git clone https://github.com/realm/SwiftLint
        cd swiftlint
        git submodule update --init --recursive
        make install
    - name: Run Swiftlint
    - uses: JanGorman/swiftlint@master
